config/routes.rb
Rails.application.routes.draw do

  get 'help/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  root :to => 'clients#index'

  resources :clients do
    collection do
      post :import
    end
  end

  get '/ping_in_map/:id', to: 'clients#ping_in_map'
  get '/seller_on_board/:id', to: 'clients#seller_on_board'

  authenticate :user do
     scope "/admin" do
        resources :clients, only: [:new, :create, :edit, :update, :destroy]
     end
  end
 end

app/models/category.rb
class Category < ActiveRecord::Base

  has_and_belongs_to_many :clients

  validates :name, uniqueness: true
  
end

app/models/client.rb
require 'csv'

class Client < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :sellers

  validates :name, presence: true
  validates :address, presence: true
  validates :CP, presence: true
  validates :zona, presence: true
  validates :client_number, presence: true

  belongs_to :user
  geocoded_by :address
  after_validation :geocode

  # Array de formatos permitidos
  ALLOW_FORMATS = ['text/csv'].freeze

  # Import CSV File
  def self.import(file)
    if file.blank? || ALLOW_FORMATS.exclude?(file.content_type)
      # Si no enviaron un archivo, o no tiene el formato correcto, devolvemos.
      return nil
    end

    CSV.foreach(file.tempfile.path, headers: true) do |row|
      client_hash = row.to_hash

      if Client.exists?(client_number: client_hash["client_number"])
        client = Client.find_by_client_number(client_hash["client_number"])
        client.update_attributes(client_hash)
      else
        Client.create!(client_hash)
      end
    end
  end

  # Export CSV File 
  def self.to_csv(attributes = column_names, options = {})
    attributes = %w{id longitude latitude client_number name address CP zona description vendedores_id seller_id }
    CSV.generate(options) do |csv|
      csv << attributes

      all.each do |client|
        csv << client.attributes.values_at(*attributes)
      end
    end
  end
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  has_and_belongs_to_many :clients
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :clients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoryController < ApplicationController

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    
    if @category.save
      redirect_to @category
    else
      render "New"
    end
  end


  def update
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to root_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @clients = Client.all
    @hash = Gmaps4rails.build_markers(@clients) do |client, marker|
      marker.lat client.latitude
      marker.lng client.longitude
      marker.infowindow client.description
    end
    

    # Format to export CSV File
    respond_to do |format|
      format.html
      format.csv { send_data @clients.to_csv }
      format.xls { send_data @clients.to_csv(col_sep: "\t")}
    end
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @client.update_attributes(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # Import CSV file
  def import
    file = params[:file]

    if file.present?
      if file.content_type.ends_with?('csv')
        begin
          Client.import(params[:file])
        rescue
          redirect_to root_path, alert: "El archivo CSV subido no respeta el formato requerido."
          return
        end
        redirect_to root_path, notice: "Lista de Clientes Importada con Exito!!!"
      else
        redirect_to root_path, alert: "Atencion: Debe subir un archivo con extension CSV!"
      end
    else
      redirect_to root_path, alert: "Debe seleccionar un archivo"
    end
  end



  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def ping_in_map
    ping = params[:id]

    return redirect_to root_path if ping == 'all'

    @clients = if ping == 'none'
                []
               else
                 category = Category.find(ping.to_i) rescue nil
                 [category.try(:clients)].flatten
               end

    if @clients.present?
      @hash = Gmaps4rails.build_markers(@clients) do |client, marker|
        marker.lat client.latitude
        marker.lng client.longitude
        marker.infowindow client.description
      end
    end

    render :index
  end

  def seller_on_board
    sell = params[:id]
    return redirect_to root_path if sell == 'all'
    
    @clients = if sell == 'none'
                 []
               else
                 seller = Seller.find(sell.to_i) rescue nil
                 [seller.try(:clients)].flatten
               end
    if @clients.present?
      @hash = Gmaps4rails.build_markers(@clients) do |client, marker|
        marker.lat client.latitude
        marker.lng client.longitude
        marker.infowindow client.description
      end
    end
    
    render :index
  end

  private
    def set_client
      begin
      @client = Client.find(params[:id])
      rescue
      render :index
      end
    end

    def client_params
      params.require(:client).permit(:latitude, :longitude, :client_number, :name, :address, :CP, :zona, :description, :vendedores_id, :seller_id)
    end
end

 

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index
  end
end

app/controllers/sellers_controller.rb
 class  SellersController < ApplicationController

  def index
    @sellers = Seller.all
  end

  def new
    @seller = Seller.New
  end

  def create
    @seller = Seller.new(seller_params)

    if @seller.save
      redirect_to @seller
    else
      render "New"
    end
  end

  def update
    @seller = Seller.find(params[:id])
  end

  def destroy
    @seller = Seller.find(params[:id])
    @seller.destroy

    redirect_to root_path
  end

  private

  def seller_params
    params.require(:seller).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :client_number %><br>
    <%= f.number_field :client_number %>
  </div>

  <div class="field">
      <%= f.label :categories %><br>
      <%= f.collection_select(:category, Category.all, :name, {:prompt => "Category"}, {:multiple => true}) %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
      <%= f.label :Vendedores %><br>
      <%= f.collection_select(:seller, Seller.all, :name, {:prompt => "Vendedores"}, {:multiple => true})%>
  </div>

  <div class="field">
    <%= f.label :CP %><br>
    <%= f.number_field :CP %>
  </div>

  <div class="field">
    <%= f.label :zona %><br>
    <%= f.text_field :zona %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/import.html.erb
<h1>the CSV file is imported successfully..!!</h1>

<%= link_to 'Go Back Home', root_path %>

app/views/clients/index.html.erb
<div class="page-header">
<table>
  <tr>
    <td>
      <div style='width: 800px;'>
          <div id="map" style='width: 800px; height: 400px;'></div>
      </div>
    </td>
    <td>
      <ul id="category_list">
        <li class="title">Categorias</li>
        <li><a href='/ping_in_map/none'>Limpiar todos</a></li>
        <% Category.all.each do |category| %>
          <li><a href=<%= "/ping_in_map/#{category.id}" %>><%= category.name %></a></li>
        <% end %>
        <li><a href='/ping_in_map/all'>Marcar Todos</a></li>
        <br>
        <li class="title">Vendedores</li>
        <li><a href='/seller_on_board/all'>Marcar Todos</a></li>
        <% Seller.all.each do |seller| %>
        <li><a href=<%="/seller_on_board/#{seller.id}" %>><%= seller.name %></a></li>
        <% end %>
      </ul>
    </td>
  </tr>
</table>

<script type="text/javascript">
 handler = Gmaps.build('Google');
 handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
     markers = handler.addMarkers(<%=raw @hash.to_json %>);
     handler.bounds.extendWith(markers);
     handler.fitMapToBounds();
 });
</script>
<br/><br/>

<h1>Lista de Clientes</h1>
</div>

<div class="table-responsive">
<table class="table table-striep table-hover">
<thead>
<tr>
 <th>Latitude</th>
 <th>Longitude</th>
 <th>Cliente</th>
 <th>Nombre</th>
 <th>Direccion</th>
 <th>Codigo Postal</th>
 <th>Zona</th>
 <th>Descripcion</th>
 <th></th>
 <th></th>
</tr>
</thead>

<tbody>
<%= content_tag_for(:tr, @clients) do |client| %>
 <tr>
   <td><%= client.latitude %></td>
   <td><%= client.longitude %></td>
   <td><%= client.client_number %></td>
   <td><%= client.name %></td>
   <td><%= client.address %></td>
   <td><%= client.CP %></td>
   <td><%= client.zona %></td>
   <td><%= client.description %></td>
   <% if signed_in? %>
   <td><%= link_to 'Show', client, class: 'link_to' %></td>
   <td><%= link_to 'Edit', "/admin/client/#{client.id}/edit", class: 'link_to' %></td>
   <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }, class: 'link_to' %></td>
 </tr><% end %>
<% end %>
</tbody>
</table>
</div>

<% if signed_in? %>
<div class="form-group">
    <h3>Importar CSV File</h3>
    <%= form_tag import_clients_path, multipart: true, class: 'form-inline' do %>
        <%= file_field_tag :file, class: '' %><br/>
        <%= submit_tag "Import CSV" , class: 'btn btn-info'%>
    <% end %>
    <h3>Agregar Nuevo Cliente</h3>
    <%= link_to "New Client", '/admin/client/new', class: 'btn btn-warning btn-sm' %>
    <h3>Download CSV File </h3>
        <%= link_to "Export CSV File", '/clients.csv', class: 'btn btn-default btn-sm' %>
    <h3>Download Excel File</h3>
    <%= link_to "Export Excel File", '/clients.xls', class: 'btn btn-default btn-sm' %> <hr/><br/>
</div
<h5>Para mayor informacion como subir los archivos extencion CSV visite el siguiente sitio<%= link_to "Aqui", '/help/index', class: 'btn btn-link btn-sm'%></h5>
<% end %>


<br/>
<style>
.link_to {
  color: grey;
}

#category_list {
  display: block;
  background-color: #6793ea;
  list-style-type: none;
  height: 400px;
  margin-top: 10px;
  width: 200px;
}

#category_list li a {
  color: white;
  margin-left: -20px;
  margin-top: 10px;
}

#category_list .title {
  font-weight: bold;
  margin-bottom: 10px;
  margin-left: -20px;
  font-size: 14pt;
  padding-top: 6px;
}

#category_list li a:hover {
  background: none !important;
  text-decoration: none;
  color: grey;
}
</style>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @client.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @client.longitude %>
</p>

<p>
  <strong>Client:</strong>
  <%= @client.client_number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Cp:</strong>
  <%= @client.CP %>
</p>

<p>
  <strong>Vendedor:</strong>
  <%= @client.seller.name %>
</p>

<p>
  <strong>Zona:</strong>
  <%= @client.zona %>
</p>

<p>
  <strong>Description:</strong>
  <%= @client.description %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/help/index.html.erb
<div class="page-header">
<h1>Como subir archivos CSV File</h1>
<br/>
<p>
    Para Subir Archivo con extencion CSV debera tener en cuenta los siguiente...
</p>
<br/>

<p>
    El formato del archivo debera tener el siguiente contexto :
</p>
<p>
    <p>En el primer renglon debera contener la siguiente informacion</p><br/>
    longitude,latitude,client_number,name,address,CP,zona,description <br/>
    -60,-31,378,Alberto,Algun lugar 12,5010,Sur,Ruby Dev <br/>
    -65,-31.4241523,379,heroku,Avenida los arboles 1000 Cordoba Argentina,5010,Sur,Ruby Dev <br/>
    -65,-31.4241523,380,Matz,Avenida duarte 2000 Cordoba Argentina,5010,Sur,Ruby Dev <br/>
    -66,-31.4241523,381,pepino,Colon 3000 Cordoba Argentina,5010,Sur,Ruby Dev <br/>
    90,20,382,betoPatricio,lejos 22,5000,Sur,Goleador-de-boca <br/>
    91,21,386,Roberto,new york 26,5010,Sur,Riquelme <br/>
</p>
<p>
   A tener en cuenta que no se dejara espacios en blanco entre comas "," y lo siguiente, si no que estara todo pegado entre si...
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Grupo Insigne Mapeo</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maps.google.com/maps/api/js?key=AIzaSyBsZMRhKqnN5aTI7CYaGhD8pRxZIezvRSA"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

  <%= favicon_link_tag 'favicon.ico'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Mapeo", "/", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="active"><a href="http://grupoinsigne.com.ar">Home</a></li></ul>
            <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to(current_user.email, '/admin') %></li>
                <li class="sign_out"><%= link_to(image_tag('cerrar.png', width: '20px'), destroy_user_session_path, method: :delete)%></li>
            <% else %>
                <li><%= link_to(' Ingresar', '/admin', class: "glyphicon glyphicon-log-in")%></li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name.to_s == 'alert' ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <p class="notice"><% notice %></p>
    <p class="alert"><% alert %></p>


  <%= yield %>

</div>
</div>
</body>
</html>

<style>
.sign_out {
  margin-left: -20px;
}
</style>